### ISSUE TITLE
Same data being imported again

### ISSUE THREAD

**Issue by tashrifbillah** [AMP-SCZ/dpimport#4]
> import.py -c ~/dpimport/examples/config.yml "/home/tb571/project_data/**/*csv"

Upon running the above twice, old data is not being bypassed, rather imported again. We need to look into the recent updates to make sure we did not cause this. I evidently remember this to be not the case last time.

**Comment by blms** [comment]
I've found the problem, not related to my updates. It's here:
https://github.com/PREDICT-DPACC/dpimport/blob/0bd776a440e18d831ecbad55410d5b529fa95702/scripts/import.py#L52-L57

The log explains exactly why this fails. First, we import the following document, `... day1to1231.csv`:
```
INFO:__main__:document does not exist or is out of date /home/bls64/dpdash-data/GENERAL/BLS/2XC43/phone/processed/BLS-2XC43-phone_surveyTimings_logbook_daily-day1to1231.csv
INFO:__main__:flipping sync to false for documents matching /home/bls64/dpdash-data/GENERAL/BLS/2XC43/phone/processed/BLS-2XC43-phone_surveyTimings_logbook_daily-day*.csv
INFO:__main__:removing all unsynced documents matching /home/bls64/dpdash-data/GENERAL/BLS/2XC43/phone/processed/BLS-2XC43-phone_surveyTimings_logbook_daily-day*.csv
INFO:__main__:importing file /home/bls64/dpdash-data/GENERAL/BLS/2XC43/phone/processed/BLS-2XC43-phone_surveyTimings_logbook_daily-day1to1231.csv
```
Then, we try to import the next document, `...day1to1232.csv`:
```
INFO:__main__:document does not exist or is out of date /home/bls64/dpdash-data/GENERAL/BLS/2XC43/phone/processed/BLS-2XC43-phone_surveyTimings_logbook_daily-day1to1232.csv
INFO:__main__:flipping sync to false for documents matching /home/bls64/dpdash-data/GENERAL/BLS/2XC43/phone/processed/BLS-2XC43-phone_surveyTimings_logbook_daily-day*.csv
INFO:__main__:removing all unsynced documents matching /home/bls64/dpdash-data/GENERAL/BLS/2XC43/phone/processed/BLS-2XC43-phone_surveyTimings_logbook_daily-day*.csv
INFO:__main__:importing file /home/bls64/dpdash-data/GENERAL/BLS/2XC43/phone/processed/BLS-2XC43-phone_surveyTimings_logbook_daily-day1to1232.csv
```
The key is the third line here. We have now removed `...day1to1231.csv` from the database. This should be fine, since it's now outdated. However, that means that next time we run DPImport, `...day1to1231.csv` will not exist. So it will try this again:

```
INFO:__main__:document does not exist or is out of date /home/bls64/dpdash-data/GENERAL/BLS/2XC43/phone/processed/BLS-2XC43-phone_surveyTimings_logbook_daily-day1to1231.csv
INFO:__main__:flipping sync to false for documents matching /home/bls64/dpdash-data/GENERAL/BLS/2XC43/phone/processed/BLS-2XC43-phone_surveyTimings_logbook_daily-day*.csv
INFO:__main__:removing all unsynced documents matching /home/bls64/dpdash-data/GENERAL/BLS/2XC43/phone/processed/BLS-2XC43-phone_surveyTimings_logbook_daily-day*.csv
INFO:__main__:importing file /home/bls64/dpdash-data/GENERAL/BLS/2XC43/phone/processed/BLS-2XC43-phone_surveyTimings_logbook_daily-day1to1231.csv
```

Deleting `day1to1232.csv`, the more up-to-date file. So it will then have to re-import that one. This means that all files with more than one matching `day*.csv` will always be reimported.

The question is: do we need to delete the outdated entries (in other words, is "probably unnecessary" wrong)? If so, we must find the most up-to-date `day*` entry and ignore all others. Otherwise the reimport will happen.

If not, it's a simple fix: just remove these lines.

**Comment by tashrifbillah** [comment]
> This means that all files with more than one matching day*.csv will always be reimported.

Good catch!

**Comment by blms** [comment]
I just tried it with those lines removed—in other words, leaving all matching `day*.csv`, including outdated ones. It seemed to work fine, as my plot on DPDash goes all the way to day 1236, which is the highest date. However, I'm a little unsure about how consistent this will be. It depends on [this function in DPDash](https://github.com/PREDICT-DPACC/dpdash/blob/34b81685a433aac8618d44e92b41b45686431e73/server/routes/index.js#L315). I need to investigate further to see how it actually decides which data to pull. (Right now it seems like it just pulls the first data set it finds, which would not necessarily be the most up to date one.)

**Comment by tashrifbillah** [comment]
Is the issue happening because of the new `*/**/*csv` pattern we invented?

**Comment by tashrifbillah** [comment]
> The question is: do we need to delete the outdated entries

A better question is--ever and anon we shall need to import new data as they come to us. When we do it, is it okay to delete seemingly outdated entries although they are not?

**Comment by blms** [comment]
> Is the issue happening because of the new `*/**/*csv` pattern we invented?

No, the glob generated for `day*.csv` (which causes the problem) is the same as before.

> A better question is--ever and anon we shall need to import new data as they come to us. When we do it, is it okay to delete seemingly outdated entries although they are not?

Definitely not okay to delete non-outdated entries. However, while it is true that those entries are currently being deleted, they are re-imported when the loop reaches them. That's because this method relies on files being read in order alphabetically. The last file in the loop matching `day*.csv` will be imported and all other DB entries matching that glob will be deleted.

To be safest, I think I will just implement a check that this day is indeed the latest day matching the glob, and delete all earlier.

**Comment by tashrifbillah** [comment]
> while it is true that those entries are currently being deleted, they are re-imported when the loop reaches them.

Right, then we are not losing anything, are we?

**Comment by blms** [comment]
Currently all files except the last one found matching the glob are deleted, assuming that the loop is indeed in alphabetical order. But that seems like a dangerous assumption, so better to implement a safety check. Also, if we check that first for every new `*day` glob, we can skip all earlier and prevent all of this re-importing.

**Comment by blms** [comment]
<details>
<summary>Outdated, see below.</summary>

@tashrifbillah What will these files look like in the real world? Can we assume that data will be entered with no overlapping days, except for the case of `day1toN` where `N` is increasing?

No overlap, for the same subject and study:
```
...day1to10.csv
...day11to100.csv
```
If we assume this is the case, then we can just import files in numerical order.

If there are overlapping days in the case of `day1toN`:
```
...day1to100.csv
...day1to101.csv
```
Then we can also check for this, and import whichever has the highest `N`.

But if there are overlapping days:
```
...day1to10.csv
...day5to41.csv
```
This presents more of a problem. We would have to rewrite DPImport a bit to only insert data for days that do not already have a datum. And it would have to be assumed that the overlapping data are identical. Unless we do some sort of file date comparison to always overwrite with the most recent.
</details>

**Comment by blms** [comment]
>  rewrite DPImport a bit to only insert data for days that do not already have a datum

I think I will just go ahead and do this. It shouldn't be too hard and that will be agnostic to the day sequence of the files entered.

**Comment by tashrifbillah** [comment]
Thanks for doing the hard work.
